import type { Product } from '../types';

export const getProductEmoji = (product: Product): string => {
  if (product.image) return product.image;
  const n = product.name.toLowerCase();
  if (n.includes('café') || n.includes('cafe') || n.includes('espresso') || n.includes('latte') || n.includes('capuchino') || n.includes('americano') || n.includes('cortado') || n.includes('macchiato')) return '☕';
  if (n.includes('té') || n.includes('te ') || n.includes('infusión') || n.includes('manzanilla') || n.includes('mate') || n.includes('hierba')) return '🍵';
  if (n.includes('frappé') || n.includes('frappe') || n.includes('bubble') || n.includes('batido') || n.includes('licuado')) return '🧋';
  if (n.includes('jugo') || n.includes('zumo') || n.includes('néctar')) return '🧃';
  if (n.includes('gaseosa') || n.includes('refresco') || n.includes('coca') || n.includes('fanta') || n.includes('pepsi')) return '🥤';
  if (n.includes('agua')) return '💧';
  if (n.includes('leche')) return '🥛';
  if (n.includes('chocolate caliente') || n.includes('cocoa')) return '🍫';
  if (n.includes('torta') || n.includes('pastel') || n.includes('brownie')) return '🍰';
  if (n.includes('cupcake') || n.includes('muffin')) return '🧁';
  if (n.includes('postre') || n.includes('pie') || n.includes('tarta')) return '🥧';
  if (n.includes('flan') || n.includes('pudín') || n.includes('pudin')) return '🍮';
  if (n.includes('galleta') || n.includes('masita') || n.includes('cookie')) return '🍪';
  if (n.includes('dona') || n.includes('buñuelo')) return '🍩';
  if (n.includes('helado') || n.includes('ice cream')) return '🍦';
  if (n.includes('pan') || n.includes('panini') || n.includes('baguette') || n.includes('bagel')) return '🥖';
  if (n.includes('waffle') || n.includes('gofre')) return '🧇';
  if (n.includes('pancake') || n.includes('hotcake') || n.includes('crepe')) return '🥞';
  if (n.includes('croissant') || n.includes('medialuna')) return '🥐';
  if (n.includes('empanada') || n.includes('salteña') || n.includes('cuñap') || n.includes('wrap') || n.includes('pita')) return '🥙';
  if (n.includes('sandwich') || n.includes('sándwich') || n.includes('tostado')) return '🥪';
  if (n.includes('hamburguesa') || n.includes('burger')) return '🍔';
  if (n.includes('hot dog') || n.includes('salchicha')) return '🌭';
  if (n.includes('pizza')) return '🍕';
  if (n.includes('ensalada') || n.includes('salad')) return '🥗';
  if (n.includes('taco') || n.includes('tortilla')) return '🌮';
  if (n.includes('burrito') || n.includes('enrollado')) return '🌯';
  if (n.includes('pollo') || n.includes('chicken') || n.includes('alita')) return '🍗';
  if (n.includes('carne') || n.includes('bistec') || n.includes('steak')) return '🥩';
  if (n.includes('desayuno')) return '🍳';
  if (n.includes('combo')) return '🍱';
  if (product.tipo === 'combo') return '🍱';
  if (product.tipo === 'elaborado') return '☕';
  return '🛒';
};
